version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: orders-db
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: orders-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,cloudwatch,logs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    
  wiremock:
    image: wiremock/wiremock
    container_name: orders-wiremock
    ports:
      - "8888:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - --verbose
      - --global-response-templating
    
  grafana:
    image: grafana/grafana
    container_name: orders-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-postgresql-datasource
      # Direct PostgreSQL connection for metrics
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres
      - GF_DATABASE_NAME=orders_db
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD=postgres

volumes:
  postgres-data:
  localstack-data:
  grafana-data:
