name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/orders-creator:latest
          no-cache: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create project directory if it doesn't exist
            mkdir -p ~/orders-creator
            cd ~/orders-creator
            
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker $USER
            fi
            
            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            fi
            
            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/orders-creator:latest
            
            # Create .env file with secrets
            cat > .env << EOL
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            ORDER_CREATED_TOPIC_ARN=${{ secrets.ORDER_CREATED_TOPIC_ARN }}
            EOL
            
            # Create or update docker-compose.yml
            cat > docker-compose.yml << EOL
            version: '3.8'
            
            services:
              orders-creator:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/orders-creator:latest
                container_name: orders-creator
                restart: always
                ports:
                  - "8080:8080"
                env_file:
                  - .env
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 10s
              
              postgres:
                image: postgres:14
                container_name: orders-db
                restart: always
                environment:
                  POSTGRES_DB: orders_db
                  POSTGRES_USER: \${DB_USERNAME}
                  POSTGRES_PASSWORD: \${DB_PASSWORD}
                ports:
                  - "5432:5432"
                volumes:
                  - postgres-data:/var/lib/postgresql/data
                healthcheck:
                  test: ["CMD", "pg_isready", "-U", "postgres"]
                  interval: 5s
                  timeout: 5s
                  retries: 5
              
              grafana:
                image: grafana/grafana
                container_name: orders-grafana
                restart: always
                ports:
                  - "3000:3000"
                environment:
                  - GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}
                  - GF_USERS_ALLOW_SIGN_UP=false
                  - GF_INSTALL_PLUGINS=grafana-postgresql-datasource
                volumes:
                  - grafana-data:/var/lib/grafana
            
            volumes:
              postgres-data:
              grafana-data:
            
            networks:
              default:
                external: false
                name: orders-network
            EOL
            
            # Create network if it doesn't exist
            sudo docker network inspect orders-network >/dev/null 2>&1 || sudo docker network create orders-network
            
            # Stop and remove existing containers
            sudo docker-compose down
            
            # Start the service with --force-recreate to ensure new images are used
            sudo docker-compose up -d --force-recreate
            
            # Clean up old images
            sudo docker image prune -af
